name: surveyapp

services:
  db_survey:
    image: postgres:latest
    container_name: survey_db
    environment:
      POSTGRES_DB: surveys
      POSTGRES_USER: Lizka
      POSTGRES_PASSWORD: 0000
    volumes:
      - data:/var/lib/postgresql/data
      #- ./sql_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5000:5000"
    networks:
      - survey_network
    command: postgres -p 5000


  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://Lizka:0000@db:5000/surveys
    networks:
      - survey_network


volumes:
  data:
    driver: local

networks:
  survey_network:
    driver: bridge

